#!/bin/bash

echo '                              \033[#;#;#m                           '
for attr in 0 1 4 5 7 8; do
    echo -ne "\033[1;37m"
    for fore in 30 31 32 33 34 35 36 37; do
        for back in 40 41 42 43 44 45 46 47; do
            printf '\033[%s;%s;%sm %01s;%02s;%02s ' $attr $fore $back $attr $fore $back
        done
		printf '\033[0;0m\n'
    done
    printf '\033[0;0m\n'
done
