#!/bin/bash -u

fail() {
    echo "$@" >&2
    exit 1
}

power=$(acpi) || fail "Failed to read power information"

if echo "$power" | grep -q "Discharging"; then
    percent=$(echo "$power" | awk  -F ', ' '{print $2}' | tr -d '%')
    if [[ $percent -lt 25 ]]; then
        notify-send "$power"
    fi
fi

exit 0
