#!/bin/sh -u

BASE_DIR=$(cd $(dirname "$0") && pwd -P)
SCRIPT_NAME=$(basename "$0")

fail() {
	echo "$@"
	exit 1
}

usage() {
        cat <<EOI
usage: git_rev [ARGS] TICKET_NUM

ARGS:
  -f, --fetch     run "git fetch" first
  -d, --delete    delete existing branch first
EOI
        return 1
    }
[ $# -eq 0 ] && {
    usage
    exit 1
}

fetch=0
delete=0
ticket=

while [ $# -gt 0 ]; do
    arg="$1"
    shift
    case "$arg" in 
        --fetch|-d)
            fetch=1
            ;;
        --delete|-d)
            delete=1
            ;;
        --fd|-df)
            fetch=1
            delete=1
            exit
            ;;
        *)
            [ -z "$ticket" ] || {
                fail "Ticket $ticket already specified"
            }
            ticket="$arg"
            ;;
    esac
done

# sanity checks!
[ -n "$ticket" ] || {
    usage
    fail "No ticket specified"
}
( echo "$ticket" | grep -qe '^[0-9]\+$' ) || {
    usage
    fail "Invalid ticket: $ticket"
}

cur_branch=$(git rev-parse --abbrev-ref HEAD)
branch=$(git branch -a | grep "/$ticket/")
branch=${branch##*origin/}

# fetch/delete first, as requested
[ $fetch -eq 1 ] && git fetch origin $branch
[ $delete -eq 1 ] && git branch -d "$branch"

# do the deed, if needed -- might already be on this branch
[ $delete -eq 0 -a "$branch" == "$cur_branch" ] || {
    git checkout "$branch"
}

# if we didn't fetch up front, do a quiet background fetch now
[ $fetch -eq 0 ] && {
    git fetch origin $branch &>/dev/null &
    disown -r
}
