#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/jonny/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# networking
nm-applet &
# background
which nitrogen 2>/dev/null && {
    nitrogen --restore
} || {
    [ -f ~/.fehbg ] && feh --bg-scale $(cat ~/.fehbg)
}

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/jonny/.fluxbox/log"
